### ISSUE TITLE
Error compiling in Linux (Linux Mint 17)

### ISSUE THREAD

**Issue by MikyGonzalez** [keebus/koji#1]
I'm getting a lot of errors, compiling with: `gcc koji.c main.c -o koji -Wextra -std=c99 -I.`

```
koji.c:(.text+0x23a): undefined reference to `_snprintf_c'
koji.c:(.text+0x274): undefined reference to `alloca'
koji.c:(.text+0x2a9): undefined reference to `_snprintf_c'
/tmp/cc7fHg6a.o: In function `lex_token_to_string':
koji.c:(.text+0x7bd): undefined reference to `_snprintf_c'
/tmp/cc7fHg6a.o: In function `allocator_page_create':
koji.c:(.text+0x25c5): undefined reference to `_allocator_page_buffer'
/tmp/cc7fHg6a.o: In function `allocator_reset':
koji.c:(.text+0x264c): undefined reference to `_allocator_page_buffer'
/tmp/cc7fHg6a.o: In function `allocator_alloc':
koji.c:(.text+0x2699): undefined reference to `_align'
koji.c:(.text+0x26ac): undefined reference to `_allocator_page_buffer'
koji.c:(.text+0x26fd): undefined reference to `_align'
/tmp/cc7fHg6a.o: In function `kc_parse_primary_expression':
koji.c:(.text+0x43a2): undefined reference to `alloca'
collect2: error: ld returned 1 exit status
```

Code is been writting using VS? I think it, and also probably some things are not portable, so is hard to port other systems.

**Comment by keebus** [comment]
Hi Miky,

correct, code has been written in VS but I planned to have a go with
clang/gcc and fix the build on linux. They seem pretty trivial issues, I'm
gonna fix it tomorrow.

Thanks for your interest in koji,
-M

2015-10-13 21:09 GMT+01:00 Miky Gonzalez <notifications@github.com>:

> I'm getting a lot of errors, compiling with: gcc koji.c main.c -o koji
> -Wextra -std=c99 -I.
>
> koji.c:(.text+0x23a): undefined reference to `_snprintf_c'
> koji.c:(.text+0x274): undefined reference to `alloca'
> koji.c:(.text+0x2a9): undefined reference to `_snprintf_c'
> /tmp/cc7fHg6a.o: In function `lex_token_to_string':
> koji.c:(.text+0x7bd): undefined reference to `_snprintf_c'
> /tmp/cc7fHg6a.o: In function `allocator_page_create':
> koji.c:(.text+0x25c5): undefined reference to `_allocator_page_buffer'
> /tmp/cc7fHg6a.o: In function `allocator_reset':
> koji.c:(.text+0x264c): undefined reference to `_allocator_page_buffer'
> /tmp/cc7fHg6a.o: In function `allocator_alloc':
> koji.c:(.text+0x2699): undefined reference to `_align'
> koji.c:(.text+0x26ac): undefined reference to `_allocator_page_buffer'
> koji.c:(.text+0x26fd): undefined reference to `_align'
> /tmp/cc7fHg6a.o: In function `kc_parse_primary_expression':
> koji.c:(.text+0x43a2): undefined reference to `alloca'
> collect2: error: ld returned 1 exit status
>
> Code is been writting using VS? I think it, and also probably some things
> are not portable, so is hard to port other systems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keebus/koji/issues/1>.
>



-- 
*Canio Massimo Tristano*

**Comment by MikyGonzalez** [comment]
Hi,

I checked new commit, and I still having errors, I know they are caused for using non-standard functions (alloca, ...)

```
/tmp/cc1wnbMX.o: In function `reportv':
koji.c:(.text+0x23f): undefined reference to `_snprintf_c'
koji.c:(.text+0x279): undefined reference to `alloca'
koji.c:(.text+0x2ae): undefined reference to `_snprintf_c'
/tmp/cc1wnbMX.o: In function `lex_token_to_string':
koji.c:(.text+0x709): undefined reference to `_snprintf_c'
/tmp/cc1wnbMX.o: In function `kc_parse_primary_expression':
koji.c:(.text+0x4357): undefined reference to `alloca'
collect2: error: ld returned 1 exit status
```

Warnings errors:

```
koji.c: In function ‘reportv’:
koji.c:195:2: warning: implicit declaration of function ‘_snprintf_c’ [-Wimplicit-function-declaration]
  uint header_length = snprintf(NULL, 0, header_format, sl.filename, sl.line, sl.column);
  ^
koji.c:197:2: warning: implicit declaration of function ‘alloca’ [-Wimplicit-function-declaration]
  char *message = alloca(header_length + body_length + 1);
  ^
koji.c:197:18: warning: initialization makes pointer from integer without a cast [enabled by default]
  char *message = alloca(header_length + body_length + 1);
                  ^
koji.c: In function ‘kc_parse_primary_expression’:
koji.c:2223:14: warning: initialization makes pointer from integer without a cast [enabled by default]
   char* id = alloca(c->lex->token_string_length + 1);
```

**Comment by keebus** [comment]
Just commited a fix for linux gcc & clang compilation.

**Comment by MikyGonzalez** [comment]
It now compile, but executing it I get `Segmentation Fault`, also compiler gives some warnings:

```
koji.c: In function ‘kc_expr_string’:
koji.c:1789:4: warning: missing initializer for field ‘data’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
    .string.data = allocator_alloc(&c->allocator, length + 1, 1),
    ^
koji.c:1744:10: note: ‘data’ declared here
    char* data;
          ^
koji.c: In function ‘kc_expr_accessor’:
koji.c:1810:4: warning: missing initializer for field ‘rhs’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
    .rhs = accessor_name_location,
    ^
koji.c:1749:8: note: ‘rhs’ declared here
    int rhs;
        ^
koji.c: In function ‘kc_expr_comparison’:
koji.c:1822:2: warning: missing initializer for field ‘rhs’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
  return (kc_expr) { type, .lhs = lhs_location, .rhs = rhs_location, .positive = test_value };
  ^
koji.c:1749:8: note: ‘rhs’ declared here
    int rhs;
        ^
koji.c: In function ‘kc_parse_primary_expression’:
koji.c:2263:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if (fn_index != -1)
```

I has tested it with Example program in README (getting segmentation fault):

```
globals.point_metatype = {
    add: def (other) {
        this.x = this.x + other.x
        this.y = this.y + other.y
    }
}
var Point = def (x, y) {
    var p = { x: x, y: y }
    set_metatype(p, globals.point_metatype)
    return p
}
var p1 = Point(10, 10)
var p2 = Point(12, 12)
p1.add(p2)
```

**Comment by keebus** [comment]
I've fixed the example in the readme. That's interesting though, on windows it reports a compilation error properly. I'll investigate the segfault on linux soon.
-M

**Comment by MikyGonzalez** [comment]
Ok, now it's working. But I don't know if I should create new issue or just use it. Just as you say, when there some syntax error on Linux, it just launch a segmentation fault.

**Comment by keebus** [comment]
I tested on latest 32bit Mint and it worked fine on both debug and release. Is your system 64bit maybe?

**Comment by MikyGonzalez** [comment]
Yes, I'm running in 64 bits arch.
